# Use the official Nginx image from the Docker Hub
FROM nginx:alpine

# Copy the content of your project into the Nginx default public directory
COPY . /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80
